# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3a1af68ab3e9579d8695333a43dfbd738216a4491cc5bb0cf9da783205131c1fee61f71b9a2f6cfddd55b6adfa13f3a5d52acc7b71174f5943692fce2961996

test:
  secret_key_base: 1c91093742b62a2acae381643e7decafa5f7c346dbdce9d5e94efbd9377f7515e4fb8694df6974d83a70415c448cbb0c3c64350590f8c962271301e2246b516c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
